server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name=org: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration

jpa:
  generate-ddl: true
  show-sql: true
  properties:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true